services:
  web:
    image: wordpress:latest
    container_name: wordpress_2
    volumes:
      - wordpress-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    ports:
      - "85:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_2
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  wordpress-data:
  mysql-data:
