name: Delete Docker Containers

on:
  workflow_dispatch:

jobs:
  deleting:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v5

      - name: Remove containers
        run: docker-compose -f Docker/docker-compose.yaml down



